from __future__ import annotations

# Role-specific raw style metrics for offline clustering.
# These are style/behaviour variables, not pure quality/conversion variables.
# Missing columns are skipped automatically by the script.

STYLE_CLUSTER_METRICS: dict[str, list[str]] = {
    "CB": [
        "Passes",
        "Short passes",
        "Long passes",
        "Progressive passes",
        "Passes forward to the final third",
        "Passes into the final third",
        "Carry",
        "Defensive challenges",
        "Tackles",
        "Interceptions",
        "Ball recoveries",
        "Loose ball recoveries",
        "Air challenges",
        "Lost balls",
        "Bad ball control",
    ],
    "FB": [
        "Passes",
        "Progressive passes",
        "Passes forward to the final third",
        "Final third entries",
        "Final third entries through pass",
        "Final third entries through carry",
        "Carry",
        "Crosses",
        "Passes into the penalty box",
        "Open passes received in the final third",
        "Dribbles",
        "Defensive challenges",
        "Tackles",
        "Ball recoveries",
        "Lost balls",
    ],
    "MF": [
        "Passes",
        "Short passes",
        "Progressive passes",
        "Passes forward to the final third",
        "Final third entries",
        "Final third entries through pass",
        "Final third entries through carry",
        "Carry",
        "Key passes",
        "Passes for a shot",
        "Chances created",
        "Open passes received",
        "Open passes received in the central third",
        "Open passes received in the final third",
        "Interceptions",
        "Ball recoveries",
        "Defensive challenges",
        "Lost balls",
    ],
    "AM": [
        "Passes",
        "Short passes",
        "Progressive passes",
        "Passes forward to the final third",
        "Final third entries",
        "Key passes",
        "Passes for a shot",
        "Chances created",
        "xA",
        "Open passes received in the final third",
        "Open passes received in the opponent's box",
        "Actions in opponent's box",
        "Carry",
        "Dribbles",
        "Dribbling in the final third",
        "Shots",
        "Lost balls",
    ],
    "W": [
        "Dribbles",
        "Dribbling in the final third",
        "Crosses",
        "Passes into the penalty box",
        "Progressive passes",
        "Final third entries",
        "Final third entries through carry",
        "Carry",
        "Open passes received",
        "Open passes received in the final third",
        "Open passes received in the opponent's box",
        "Actions in opponent's box",
        "Shots",
        "Shots from the penalty area",
        "Key passes",
        "Passes for a shot",
        "Defensive challenges",
        "Ball recoveries",
        "Lost balls",
    ],
    "FW": [
        "Shots",
        "Shots from the penalty area",
        "xG (expected goals)",
        "Actions in opponent's box",
        "Open passes received",
        "Open passes received in the final third",
        "Open passes received in the opponent's box",
        "Air challenges",
        "Attacking challenges",
        "Defensive challenges",
        "Dribbles",
        "Key passes",
        "Passes for a shot",
        "Passes",
        "Lost balls",
    ],
}

DEFAULT_K_BY_ROLE: dict[str, int] = {
    "CB": 5,
    "FB": 5,
    "MF": 6,
    "AM": 5,
    "W": 6,
    "FW": 5,
}
