from __future__ import annotations

# Role-specific raw style metrics for the future offline clustering step.
# These are intentionally volume/style variables rather than pure performance/conversion metrics.
STYLE_CLUSTER_METRICS: dict[str, list[str]] = {
    "CB": [
        "Passes",
        "Long passes",
        "Progressive passes",
        "Passes forward to the final third",
        "Defensive challenges",
        "Tackles",
        "Interceptions",
        "Ball recoveries",
        "Air challenges",
        "Lost balls",
    ],
    "FB": [
        "Progressive passes",
        "Passes forward to the final third",
        "Final third entries",
        "Final third entries through carry",
        "Carry",
        "Crosses",
        "Passes into the penalty box",
        "Defensive challenges",
        "Tackles",
        "Ball recoveries",
        "Dribbles",
    ],
    "MF": [
        "Passes",
        "Short passes",
        "Progressive passes",
        "Passes forward to the final third",
        "Final third entries",
        "Carry",
        "Key passes",
        "Passes for a shot",
        "Interceptions",
        "Ball recoveries",
        "Lost balls",
    ],
    "AM": [
        "Open passes received in the final third",
        "Open passes received in the opponent's box",
        "Key passes",
        "Passes for a shot",
        "Chances created",
        "xA",
        "Progressive passes",
        "Final third entries",
        "Carry",
        "Dribbles",
        "Actions in opponent's box",
        "Lost balls",
    ],
    "W": [
        "Dribbles",
        "Dribbling in the final third",
        "Crosses",
        "Passes into the penalty box",
        "Final third entries through carry",
        "Carry",
        "Open passes received in the final third",
        "Open passes received in the opponent's box",
        "Actions in opponent's box",
        "Shots",
        "Defensive challenges",
        "Ball recoveries",
        "Lost balls",
    ],
    "FW": [
        "Shots",
        "Shots from the penalty area",
        "xG (expected goals)",
        "Actions in opponent's box",
        "Open passes received",
        "Open passes received in the final third",
        "Open passes received in the opponent's box",
        "Air challenges",
        "Attacking challenges",
        "Defensive challenges",
        "Key passes",
        "Passes for a shot",
        "Lost balls",
    ],
}
